# Site settings
title: Tyler Reny
email: ttreny@gmail.com	
description: >
 Claremont Graduate University   
 150 E 10th St, 
 Claremont, CA 91711
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tylerreny.github.io" # the base hostname & protocol for your site
twitter_username: tylerreny	
github_username:  tylerreny
encoding: UTF-8
# Build settings
markdown: kramdown

