# Site settings
title: Tyler Reny
email: ttreny@gmail.com	
description: >
 Washington University in St. Louis 
 Weidenbaum Center
 CB 1027, Seigle 187
 One Brookings Drive
 St. Louis, MO 63130
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tylerreny.github.io" # the base hostname & protocol for your site
twitter_username: tylerreny	
github_username:  tylerreny
encoding: UTF-8
# Build settings
markdown: kramdown

